/**
 * Environment variable sync functions
 */

import { existsSync, writeFileSync, readFileSync } from 'fs'
import dotenv from 'dotenv'
import { makeAuthenticatedRequest } from '../utils.js'
import { ENV_FILE } from './constants.js'

/**
 * Parse cx.env file content into an object
 * @param {string} content - File content
 * @returns {Object} Key-value pairs
 */
export function parseEnvFile(content) {
	if (!content) return {}
	const buf = Buffer.from(content)
	return dotenv.parse(buf)
}

/**
 * Serialize env object to cx.env file format
 * @param {Object} envObj - Key-value pairs
 * @returns {string} File content
 */
export function serializeEnvFile(envObj) {
	const lines = ['# ConnexCS Environment Variables', '# Auto-generated by cx-tools', '']
	const sortedKeys = Object.keys(envObj).sort()
	
	for (const key of sortedKeys) {
		const value = envObj[key]
		// Quote values that contain spaces or special characters
		if (value.includes(' ') || value.includes('=') || value.includes('#')) {
			lines.push(`${key}="${value}"`)
		} else {
			lines.push(`${key}=${value}`)
		}
	}
	
	return lines.join('\n') + '\n'
}

/**
 * Fetch remote environment variables
 * @param {boolean} silent - Whether to suppress output
 * @returns {Promise<Object>} Key-value pairs of remote env vars
 */
export async function fetchRemoteEnvVars(silent = false) {
	const appId = process.env.APP_ID
	if (!appId) {
		return { success: false, error: 'No APP_ID configured' }
	}
	
	const endpoint = `setup/var?app_id=${appId}`
	const result = await makeAuthenticatedRequest(endpoint, 'GET', null, silent)
	
	if (!result.success) {
		return { success: false, error: result.error }
	}
	
	const data = Array.isArray(result.data) ? result.data : []
	const envObj = {}
	for (const item of data) {
		envObj[item.key] = item.value
	}
	
	return { success: true, data: envObj, rawData: data }
}

/**
 * Read local cx.env file
 * @returns {Object} Key-value pairs or empty object if file doesn't exist
 */
export function readLocalEnvFile() {
	if (!existsSync(ENV_FILE)) {
		return {}
	}
	const content = readFileSync(ENV_FILE, 'utf-8')
	return parseEnvFile(content)
}

/**
 * Write local cx.env file
 * @param {Object} envObj - Key-value pairs
 */
export function writeLocalEnvFile(envObj) {
	// If no env vars, create an example file
	if (Object.keys(envObj).length === 0) {
		const exampleContent = [
			'# ConnexCS Environment Variables',
			'# Auto-generated by cx-tools',
			'#',
			'# Add your environment variables below in KEY=VALUE format',
			'# Example:',
			'#KEY="My complicated value with spaces and # symbols"',
			'#HELLO=WORLD',
			''
		].join('\n')
		writeFileSync(ENV_FILE, exampleContent, 'utf-8')
		return
	}
	
	const content = serializeEnvFile(envObj)
	writeFileSync(ENV_FILE, content, 'utf-8')
}

/**
 * Update a single key in the local cx.env file
 * @param {string} key - The key to set
 * @param {string} value - The value to set
 */
export function updateLocalEnvKey(key, value) {
	const envObj = readLocalEnvFile()
	envObj[key] = value
	writeLocalEnvFile(envObj)
}

/**
 * Remove a key from the local cx.env file
 * @param {string} key - The key to remove
 */
export function removeLocalEnvKey(key) {
	const envObj = readLocalEnvFile()
	if (key in envObj) {
		delete envObj[key]
		writeLocalEnvFile(envObj)
	}
}

/**
 * Pull environment variables from remote to local cx.env file
 * @param {boolean} silent - Whether to suppress output
 * @param {boolean} preview - If true, only show what would be pulled
 * @returns {Promise<Object>} Results with counts and diffs
 */
export async function pullEnvVars(silent = false, preview = false) {
	const remoteResult = await fetchRemoteEnvVars(silent)
	
	if (!remoteResult.success) {
		return { success: false, error: remoteResult.error, pulled: 0, total: 0, diffs: [] }
	}
	
	const remoteEnv = remoteResult.data
	const localEnv = readLocalEnvFile()
	
	const remoteKeys = Object.keys(remoteEnv)
	const localKeys = Object.keys(localEnv)
	
	// Find differences
	const diffs = []
	const allKeys = new Set([...remoteKeys, ...localKeys])
	
	for (const key of allKeys) {
		const remoteVal = remoteEnv[key]
		const localVal = localEnv[key]
		
		if (remoteVal !== undefined && localVal === undefined) {
			diffs.push({ key, type: 'add', remoteVal, localVal: null })
		} else if (remoteVal === undefined && localVal !== undefined) {
			diffs.push({ key, type: 'remove', remoteVal: null, localVal })
		} else if (remoteVal !== localVal) {
			diffs.push({ key, type: 'change', remoteVal, localVal })
		}
	}
	
	if (preview) {
		return { success: true, remoteEnv, localEnv, pulled: 0, total: remoteKeys.length, diffs }
	}
	
	// Write remote env to local file
	writeLocalEnvFile(remoteEnv)
	
	return { success: true, remoteEnv, localEnv, pulled: remoteKeys.length, total: remoteKeys.length, diffs }
}

/**
 * Push environment variables from local cx.env file to remote
 * @param {boolean} silent - Whether to suppress output
 * @param {boolean} preview - If true, only analyze what would be pushed
 * @returns {Promise<Object>} Results with changes to make
 */
export async function pushEnvVars(silent = false, preview = false) {
	const appId = process.env.APP_ID
	if (!appId) {
		return { success: false, error: 'No APP_ID configured', toCreate: [], toUpdate: [], toDelete: [] }
	}
	
	const remoteResult = await fetchRemoteEnvVars(silent)
	
	if (!remoteResult.success) {
		return { success: false, error: remoteResult.error, toCreate: [], toUpdate: [], toDelete: [] }
	}
	
	const remoteEnv = remoteResult.data
	const rawData = remoteResult.rawData
	const localEnv = readLocalEnvFile()
	
	// Build a map of remote keys to their IDs
	const remoteIdMap = {}
	for (const item of rawData) {
		remoteIdMap[item.key] = item.id
	}
	
	const toCreate = []
	const toUpdate = []
	const toDelete = []
	
	// Find what needs to be created or updated
	for (const key of Object.keys(localEnv)) {
		const localVal = localEnv[key]
		const remoteVal = remoteEnv[key]
		
		if (remoteVal === undefined) {
			toCreate.push({ key, value: localVal })
		} else if (remoteVal !== localVal) {
			toUpdate.push({ key, value: localVal, id: remoteIdMap[key] })
		}
	}
	
	// Find what needs to be deleted (exists remote but not local)
	for (const key of Object.keys(remoteEnv)) {
		if (localEnv[key] === undefined) {
			toDelete.push({ key, id: remoteIdMap[key] })
		}
	}
	
	if (preview) {
		return { success: true, toCreate, toUpdate, toDelete, localEnv, remoteEnv }
	}
	
	// Execute the changes
	let successCount = 0
	
	// Create new variables
	for (const item of toCreate) {
		const body = { key: item.key, value: item.value, app_id: appId }
		const result = await makeAuthenticatedRequest('setup/var', 'POST', body, true)
		if (result.success) {
			if (!silent) console.log(`✅ Created ${item.key}`)
			successCount++
		} else {
			console.error(`❌ Failed to create ${item.key}: ${result.error}`)
		}
	}
	
	// Update existing variables
	for (const item of toUpdate) {
		const body = { key: item.key, value: item.value, app_id: appId }
		const result = await makeAuthenticatedRequest(`setup/var/${item.id}`, 'PUT', body, true)
		if (result.success) {
			if (!silent) console.log(`✅ Updated ${item.key}`)
			successCount++
		} else {
			console.error(`❌ Failed to update ${item.key}: ${result.error}`)
		}
	}
	
	// Delete removed variables
	for (const item of toDelete) {
		const result = await makeAuthenticatedRequest(`setup/var/${item.id}`, 'DELETE', null, true)
		if (result.success) {
			if (!silent) console.log(`✅ Deleted ${item.key}`)
			successCount++
		} else {
			console.error(`❌ Failed to delete ${item.key}: ${result.error}`)
		}
	}
	
	return { success: true, toCreate, toUpdate, toDelete, successCount, totalChanges: toCreate.length + toUpdate.length + toDelete.length }
}
